{% set name = "pdbstore" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 579f5adbc2dfc4352f04b2962748c6daf24d3b16eed0dfb286bd3c7075a2ed1e

build:
  noarch: python
  number: 0
  entry_points:
    - pdbstore=pdbstore.cli.cli:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - colorama
    - pefile
    - Jinja2

test:
  source_files:
    - tests/
    - setup.py
  imports:
    - pdbstore
  commands:
    - pytest ./tests/unit
    - pytest ./tests/cli
    - pip check
  requires:
    - pip
    - mock
    - coverage
    - pytest==7.1.2
    - pytest-cov
    - pytest-subprocess
    - wheel==0.41.2
    - setuptools>=61.0.0

about:
  home: "https://github.com/crabisoft/pdbstore"
  license: MIT
  license_family: MIT
  license_file: COPYING
  description: "Command-line utility to manage PDB and PE files through local symbol store on Windows, Linux and MacOS"
  summary: "manage PDB and PE files through a local symbols store"
  doc_url: "https://pdbstore.readthedocs.io"
  dev_url: "https://github.com/crabisoft/pdbstore"

extra:
  recipe-maintainers:
    - TheCrab13
